In [1]:
import pandas as pd 
import mlflow 
import mlflow.sklearn

In [21]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing

In [8]:
from urllib.parse import urlparse

In [3]:
housing = fetch_california_housing()

In [4]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [5]:
data = pd.DataFrame(housing.data,columns= housing.feature_names)
data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [6]:
data['price'] = housing.target

In [7]:
data

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [9]:
## Depandant + indepandant values

In [10]:
X = data.drop(columns = ["price"])

In [11]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [14]:
y = data['price']

In [15]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: price, Length: 20640, dtype: float64

###### Train test split

In [16]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.20)

##### Hyperparameter_tuning

In [29]:
def hyperparametr_tuning(x_train,y_train,param):
    rf = RandomForestRegressor()
    grid_search = GridSearchCV(estimator=rf,param_grid=param,cv=3,n_jobs=-1,verbose=2,scoring="neg_mean_squared_error")
    grid_search.fit(x_train,y_train)

    return grid_search

##### Model schemas  define with signatures

In [17]:
from mlflow.models import infer_signature

In [18]:
signature = infer_signature(x_train,y_train)

In [19]:
# define  prameters

In [20]:
param = {
    'n_estimators': [100, 200],
    'max_depth': [5, 10, None],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}

In [26]:
## mlflow exp

In [30]:
with mlflow.start_run():
    #hypermarater tuning 
    grid_search = hyperparametr_tuning(x_train,y_train,param)
    # get best model 
    best_model = grid_search.best_estimator_
    ## evalute the model 

    y_pred = best_model.predict(x_test)
    mse = mean_squared_error(y_test,y_pred)

Fitting 3 folds for each of 24 candidates, totalling 72 fits

In [32]:
## log best parameter 
### Log best parameters and metrics
#mlflow.log_param("best_n_estimators", grid_search.best_params_['n_estimators'])
#mlflow.log_param("best_max_depth", grid_search.best_params_['max_depth'])
#mlflow.log_param("best_min_samples_split", grid_search.best_params_['min_samples_split'])
#mlflow.log_param("best_min_samples_leaf", grid_search.best_params_['min_samples_leaf'])
#mlflow.log_metric("mse", mse)

In [33]:
# Log all best parameters in one line
mlflow.log_params(grid_search.best_params_)

# Log your metric
mlflow.log_metric("mse", mse)

In [34]:
## tracking ui

In [40]:
mlflow.set_tracking_uri(uri = "http://127.0.0.1:5000")
tracking_url_type_store = urlparse(mlflow.get_tracking_uri()).scheme

if tracking_url_type_store != "file":
    mlflow.sklearn.log_model(best_model,"model",registered_model_name= "best randomforestmodel")

else :
    mlflow.sklearn.log_model(best_model,"model",signature=signature)


print (f"best hyperparameter :{grid_search.best_params_}")
print (f"mean sqr error :{mse}")

2026/03/05 14:45:52 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/03/05 14:45:52 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
Successfully registered model 'best randomforestmodel'.
2026/03/05 14:46:01 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: best randomforestmodel, version 1

best hyperparameter :{'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
mean sqr error :0.2609271103024151

Created version '1' of model 'best randomforestmodel'.

In [ ]:

## validate model # make predict 
model_uri = f"runs:/{mlflow.active_run().info.run_id}/model"
loaded_model = mlflow.sklearn.load_model(model_uri)

new_predictions = loaded_model.predict(x_test)

In [45]:
new_predictions

array([1.245025  , 2.64268015, 1.6014102 , ..., 1.86098565, 1.474105  ,
       2.56214505], shape=(4128,))

In [47]:
model_name = "best randomforestmodel"
model_version = 1 
model_uri = f"models:/{model_name}/{model_version}"
registered_model = mlflow.pyfunc.load_model(model_uri)

# Predict
val_preds = registered_model.predict(x_test)
val_preds

array([1.245025  , 2.64268015, 1.6014102 , ..., 1.86098565, 1.474105  ,
       2.56214505], shape=(4128,))